# **10 minutes to pandas**
* https://pandas.pydata.org/docs/user_guide/10min.html
* pip install numpy, pandas

In [1]:
import numpy  as np
import pandas as pd

# **Basic data structures (기본구조)**

* <font color=red> <b> Series: 1차(one-dimensional) 데이터
* <font color=red> <b> DataFrame: 2차(two-dimensional) 데이터 (like table)
* [N]차 : N차원을 말하는 것

<img src="https://miro.medium.com/v2/resize:fit:1100/format:webp/1*OaUbgSxKnC_kaRj0H6vK5Q.jpeg" widcth=400>

<pre>      단일값[0]       리스트, 튜플, 딕[1]        Series[1]              Dataframe[2]                        Tensor[3]

In [2]:
(5) + 10    #(5) = 단일값

15

In [3]:
# row vector : 리스트/튜플/딕처럼 가로로 출력
# column vector : 세로로 출력

# **C : 생성**
* pd.Series
* pd.DataFrame

In [4]:
mylist = pd.Series([1, 3, 5, np.nan, 6, 8])
print(mylist)

s = pd.Series(mylist)
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [5]:
mylist = [ [1, 3, 5, np.nan, 6, 8] ,
           [1, 3, 5, np.nan, 6, 8] ,
           [1, 3, 5, np.nan, 6, 8] 
         ]

df = pd.DataFrame (mylist)
print(df)

   0  1  2   3  4  5
0  1  3  5 NaN  6  8
1  1  3  5 NaN  6  8
2  1  3  5 NaN  6  8

In [6]:
mylist = [ [1, 3, 5, np.nan, 6, 8] ,
           [1, 3, 5, np.nan, 6, 8] ,
           [1, 3, 5, np.nan, 6, 8]    # nan = 없는값, 입력/수정 안 되는 진짜 없는 거 (여러 행열 중에 non이 하나라도 있으면 아예 연산 불가)
         ]

df = pd.DataFrame (mylist, index=[10,20,30], columns=['a','b','c','d','e','f'])   # 각 행열에 네이밍
print(df)

df   #print 없이 하면 진짜 표처럼 예쁘게!

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

In [7]:
df2 = pd.DataFrame (mylist, index=[10,20,30], columns=['a','b','c','d','e','f'])
df2

df2.iloc[0:2, 2:]

    c   d  e  f
10  5 NaN  6  8
20  5 NaN  6  8

In [8]:
df2.loc[10:20, "c":"f"]

    c   d  e  f
10  5 NaN  6  8
20  5 NaN  6  8

In [9]:
df.dtypes

a      int64
b      int64
c      int64
d    float64
e      int64
f      int64
dtype: object

In [10]:
mydict = { "a":[1,1,1], "b":[3,3,3], "c":[5,5,5] }      #컬럼 네이밍을 abc로 지정해버림 ( i&c 불필요)
df = pd.DataFrame(mydict)
df

   a  b  c
0  1  3  5
1  1  3  5
2  1  3  5

In [11]:
mylist2 = [ [1, 2, 3],
            [2, 3, 4],
            [3, 4, 5] ]
df = pd.DataFrame(mylist2)
df

   0  1  2
0  1  2  3
1  2  3  4
2  3  4  5

In [12]:
mydict2 = { "title":"ddd", "a":[2,4,6], "N":["dd", "ss", "ff"] }
df = pd.DataFrame(mydict2)
df

  title  a   N
0   ddd  2  dd
1   ddd  4  ss
2   ddd  6  ff

In [13]:
df.head()
df

  title  a   N
0   ddd  2  dd
1   ddd  4  ss
2   ddd  6  ff

# **Viewing data**
* https://www.kaggle.com/datasets/arunjathari/bostonhousepricedata
* <font color=red><b>df.info() </b></font>
* df.shape   : 행*열
* df.index   : 인덱스
* df.columns : 컬럼이름
* df.head()  : 앞에서부터 몇개
* df.tail()  : 뒤에서부터 몇개

<pre>
| **CRIM**    | 범죄율               | 지역별 1인당 범죄율                   
| **ZN**      | 주거지역 비율        | 25,000 sq.ft 초과 주거용 토지 비율    
| **INDUS**   | 비소매 상업지역 비율  | 비소매업 용도의 토지 비율             
| **CHAS**    | 찰스강 인접 여부     | 찰스강에 접하면 **1**, 아니면 **0**   
| **NOX**     | 일산화질소 농도      | 대기오염 정도를 나타내는 질소산화물 농도
| **RM**      | 평균 방 개수         | 주택 한 채당 평균 방(Room) 수             
| **AGE**     | 오래된 주택 비율     | 1940년 이전에 지어진 주택 비율             
| **DIS**     | 고용센터까지 거리    | 보스턴의 주요 고용센터 5곳까지의 가중 거리 
| **RAD**     | 고속도로 접근성      | 방사형 고속도로 접근성 지수              
| **TAX**     | 재산세율             | $10,000당 재산세율                
| **PTRATIO** | 학생/교사 비율       | 지역별 학생 대 교사 비율               
| **B**       | 인구 관련 변수       | 원본 데이터에서 흑인 인구 비율을 변환해 만든 변수 
| **LSTAT**   | 저소득층 비율        | 낮은 사회경제적 지위 인구의 비율(%)        
| **MEDV**    | 주택가격             | 주택가격 중앙값, 단위는 **$1,000**

In [14]:
df = pd.read_csv("../datas/Boston-house-price-data.csv")    #csv = comma로 분리할 수 있는 데이터
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

In [15]:
df.shape        #행*열 정보

(506, 14)

In [16]:
df.index       #인덱스 정보

RangeIndex(start=0, stop=506, step=1)

In [17]:
df.columns     #컬럼 이름

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='str')

In [18]:
df.info()    
#data의 종합 정보 조회
#null=nan, non-null = 빈 칸 없이 꽉 차있다

<class 'pandas.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [19]:
df.head(10)    #앞에서부터 10개

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10,18.9

In [20]:
df.tail(10)    #뒤에서부터 10개

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
496,0.28960,0.0,9.69,0,0.585,5.390,72.9,2.7986,6,391.0,19.2,396.90,21.14,19.7
497,0.26838,0.0,9.69,0,0.585,5.794,70.6,2.8927,6,391.0,19.2,396.90,14.10,18.3
498,0.23912,0.0,9.69,0,0.585,6.019,65.3,2.4091,6,391.0,19.2,396.90,12.92,21.2
499,0.17783,0.0,9.69,0,0.585,5.569,73.5,2.3999,6,391.0,19.2,395.77,15.10,17.5
500,0.22438,0.0,9.69,0,0.585,6.027,79.7,2.4982,6,391.0,19.2,396.90,14.33,16.8
501,0.06263,0.0,11.93,0,0.573,6.593,69.1,2.4786,1,273.0,21.0,391.99,9.67,22.4
502,0.04527,0.0,11.93,0,0.573,6.120,76.7,2.2875,1,273.0,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0,0.573,6.976,91.0,2.1675,1,273.0,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0,0.573,6.794,89.3,2.3889,1,273.0,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0,0.573,6.030,80.8,2.5050,1,273.0,21.0,396.90,7.88,11.9

# **Selection**
* <font color=red> <b>  [ ]
* df.loc()  /  df.iloc()   :  표 형식으로 추출 (N줄 * N칸)
* df.at()  /  df.iat()     :  셀 형식으로 추출 
  * i = index, 이름으로 가져올지 / 번째로 가져올지 의 차이

In [21]:
df = df[0:10].copy()    #연습용 샘플링 (10개만 사용)

In [22]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10,18.9

In [23]:
df.shape

(10, 14)

In [24]:
df["B"]    #1개면 []

0    396.90
1    396.90
2    392.83
3    394.63
4    396.90
5    394.12
6    395.60
7    396.90
8    386.63
9    386.71
Name: B, dtype: float64

In [25]:
df[["CRIM", "B"]]   #2개 조회는 [[ ]] : 시리즈가 합쳐진 게 DataFrame, DataFrame은 2차

      CRIM       B
0  0.00632  396.90
1  0.02731  396.90
2  0.02729  392.83
3  0.03237  394.63
4  0.06905  396.90
5  0.02985  394.12
6  0.08829  395.60
7  0.14455  396.90
8  0.21124  386.63
9  0.17004  386.71

## **슬라이싱**
* 표 형식으로 가져오기 (행*열)

In [26]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10,18.9

In [27]:
df[0:2]   #행만 적용

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.9,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.9,9.14,21.6

## **loc / iloc**

In [28]:
df.iloc[0:2, 0:3]

      CRIM    ZN  INDUS
0  0.00632  18.0   2.31
1  0.02731   0.0   7.07

In [29]:
df.iloc[2:5, 2:5]

   INDUS  CHAS    NOX
2   7.07     0  0.469
3   2.18     0  0.458
4   2.18     0  0.458

In [30]:
df.loc[2:5, "INDUS":"NOX"]    
# loc은 슬라이싱 마지막도 포함됨

   INDUS  CHAS    NOX
2   7.07     0  0.469
3   2.18     0  0.458
4   2.18     0  0.458
5   2.18     0  0.458

### <font color=blue> <b> 골라서 가져오기

In [31]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10,18.9

In [32]:
df.iloc[ [0,2,4], [0,1,2,-1] ]    #[0,2,4], [0,1,2,-1]는 리스트(인덱스 번호) / 바깥 []는 버티컬

      CRIM    ZN  INDUS  MEDV
0  0.00632  18.0   2.31  24.0
2  0.02729   0.0   7.07  34.7
4  0.06905   0.0   2.18  36.2

In [33]:
df.loc[ [0,2,4], ["CRIM","ZN","INDUS","MEDV"] ]    #loc은 인덱스 번호 X, 인덱스 "값"으로

      CRIM    ZN  INDUS  MEDV
0  0.00632  18.0   2.31  24.0
2  0.02729   0.0   7.07  34.7
4  0.06905   0.0   2.18  36.2

## **at / iat**
* 특정 칸만 가져오기

In [34]:
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2
5,0.02985,0.0,2.18,0,0.458,6.430,58.7,6.0622,3,222.0,18.7,394.12,5.21,28.7
6,0.08829,12.5,7.87,0,0.524,6.012,66.6,5.5605,5,311.0,15.2,395.60,12.43,22.9
7,0.14455,12.5,7.87,0,0.524,6.172,96.1,5.9505,5,311.0,15.2,396.90,19.15,27.1
8,0.21124,12.5,7.87,0,0.524,5.631,100.0,6.0821,5,311.0,15.2,386.63,29.93,16.5
9,0.17004,12.5,7.87,0,0.524,6.004,85.9,6.5921,5,311.0,15.2,386.71,17.10,18.9

In [35]:
print( df.iat[0, 1] )   #인덱스 번호로

18.0

In [36]:
print( df.at[0, "ZN"] ) #행열 이름으로

18.0

## **index 값 : int vs str 주의!**

In [37]:
df3 = pd.DataFrame( {"a" : [1,2,3], "b":[10,20,30],} , index=["10","20","30"] )
df3

    a   b
10  1  10
20  2  20
30  3  30

In [38]:
df3.index      #행 str 타입

Index(['10', '20', '30'], dtype='str')

In [39]:
df3 = pd.DataFrame( {"a" : [1,2,3], "b":[10,20,30],} , index=[10,20,30] )
df3.index     #행 int 타입

Index([10, 20, 30], dtype='int64')

# **Missing data**
* 결측 : NaN, null, np.nan
* <font color=red><b>fillna() : 채우기(보간)
* <font color=red><b>dropna() : 버리기
* <font color=red><b>isna() : 결측체크

In [40]:
mylist = [ [1, 3, 5, np.nan, 6, 8] ,
           [1, 3, 5, np.nan, 6, 8] ,
           [1, 3, 5, np.nan, 6, 8]
         ]

df2 = pd.DataFrame (mylist, index=[10,20,30], columns=['a','b','c','d','e','f']) 

df2

    a  b  c   d  e  f
10  1  3  5 NaN  6  8
20  1  3  5 NaN  6  8
30  1  3  5 NaN  6  8

In [41]:
df2.info()

<class 'pandas.DataFrame'>
Index: 3 entries, 10 to 30
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
 3   d       0 non-null      float64
 4   e       3 non-null      int64
 5   f       3 non-null      int64
dtypes: float64(1), int64(5)
memory usage: 168.0 bytes

## **컬럼 가감산**

In [42]:
df2["a"] + 10

10    11
20    11
30    11
Name: a, dtype: int64

In [43]:
df2["a"] + df2["b"]

10    4
20    4
30    4
dtype: int64

In [44]:
df2["xx"] = df2["a"] + df2["b"]    # a + b를 추가한 XX 열에 대입
df2

    a  b  c   d  e  f  xx
10  1  3  5 NaN  6  8   4
20  1  3  5 NaN  6  8   4
30  1  3  5 NaN  6  8   4

* <font color=red> <b> 결측이 있는 컬럼은 어떠한 연산을 해도 결측이다

In [45]:
df2["a"] + df2["d"]

10   NaN
20   NaN
30   NaN
dtype: float64

## **결측 찾기**

In [46]:
df2.isna()     #결측 위치

        a      b      c     d      e      f     xx
10  False  False  False  True  False  False  False
20  False  False  False  True  False  False  False
30  False  False  False  True  False  False  False

In [47]:
df2.isna().sum()     #결측 위치와 토탈 개수

a     0
b     0
c     0
d     3
e     0
f     0
xx    0
dtype: int64

In [48]:
df2.info()    #이건 결측이 아닌 것을 카운트
# Tip : 3 entries  > 여기 값과 non-null 값 비교

<class 'pandas.DataFrame'>
Index: 3 entries, 10 to 30
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      int64
 2   c       3 non-null      int64
 3   d       0 non-null      float64
 4   e       3 non-null      int64
 5   f       3 non-null      int64
 6   xx      3 non-null      int64
dtypes: float64(1), int64(6)
memory usage: 192.0 bytes

## **결측 채우기(보간)**

In [49]:
df2.fillna(0)

    a  b  c    d  e  f  xx
10  1  3  5  0.0  6  8   4
20  1  3  5  0.0  6  8   4
30  1  3  5  0.0  6  8   4

In [50]:
df2            #위에는 단순 print라서 안 먹히는 것

    a  b  c   d  e  f  xx
10  1  3  5 NaN  6  8   4
20  1  3  5 NaN  6  8   4
30  1  3  5 NaN  6  8   4

In [51]:
df2.fillna(0, inplace=True)    #0으로, inplace : 원본에 덮어씌워라 (inplace 없이 하면 눈으로만 확인됨)

    a  b  c    d  e  f  xx
10  1  3  5  0.0  6  8   4
20  1  3  5  0.0  6  8   4
30  1  3  5  0.0  6  8   4

In [52]:
df2 = df2.fillna(0)       #보간한 걸 다시  df2에 대입
df2

    a  b  c    d  e  f  xx
10  1  3  5  0.0  6  8   4
20  1  3  5  0.0  6  8   4
30  1  3  5  0.0  6  8   4

## **결측 삭제**
* <font color=red> df.dropna(axis=0) : 행 지우기
* <font color=red> df.dropna(axis=1) : 열 지우기
* <font color=red> df.dropna(subset=["컬럼이름"]) : 컬럼을 기준으로 결측이 있는 행 삭제
* <font color=red> df.drop(columns=["컬럼이름"]) : 컬럼 전체 삭제

In [53]:
mylist = [ [1, 3, 5, np.nan, 6, 8] ,
           [1, 3, np.nan, 5, np.nan, 8] ,
           [1, 3, np.nan, 6, 7, 8] ,
           [1, 3, 5, 6, 7, 8] ,
         ]

df2 = pd.DataFrame (mylist, index=[10,20,30,40], columns=['a','b','c','d','e','f']) 

df33 = df2.copy()
df44 = df2.copy()
df55 = df2.copy()

* **df.dropna(axis=0) : 행 지우기**
* 결측이 있는 행 삭제

In [54]:
df33

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
20  1  3  NaN  5.0  NaN  8
30  1  3  NaN  6.0  7.0  8
40  1  3  5.0  6.0  7.0  8

In [55]:
df33.dropna(axis=0)

    a  b    c    d    e  f
40  1  3  5.0  6.0  7.0  8

* **df.dropna(axis=1) : 열 지우기**
* 결측이 있는 열 삭제

In [56]:
df44

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
20  1  3  NaN  5.0  NaN  8
30  1  3  NaN  6.0  7.0  8
40  1  3  5.0  6.0  7.0  8

In [57]:
df44.dropna(axis=1)

    a  b  f
10  1  3  8
20  1  3  8
30  1  3  8
40  1  3  8

* **df.dropna(subset=["컬럼이름"]) : 컬럼을 기준으로 결측이 있는 행 삭제**

In [58]:
df55

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
20  1  3  NaN  5.0  NaN  8
30  1  3  NaN  6.0  7.0  8
40  1  3  5.0  6.0  7.0  8

In [59]:
df55.dropna(subset=["c"])       #c열 20,30행에 결측이 있으니 행 두줄 삭제

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
40  1  3  5.0  6.0  7.0  8

* **df.drop(columns=["컬럼이름"]) : 컬럼 전체 삭제**
* 결측과 상관 없음

In [60]:
df55 = df55.dropna(subset=["c"])    #dropna는 subset
df55

    a  b    c    d    e  f
10  1  3  5.0  NaN  6.0  8
40  1  3  5.0  6.0  7.0  8

In [61]:
df55.drop(columns=["a", "b"])       #drop은 columns

      c    d    e  f
10  5.0  NaN  6.0  8
40  5.0  6.0  7.0  8

# **stat.(statistics, 통계)**

In [62]:
df = df[0:5].copy()    #연습용 5개만 카피

## **describe() : 상세보기**

In [63]:
df.describe()
#mean : 평균
# std : 표준편차
# min / max : 최소/최대값
# 25/50/75 : 4분위수(Quaters)  * N번째의 의미임 (=50%와 평균은 다름)
# ==> mean(평균)은 0.032 이지만, 딱 정중앙에 있는 50%의 값은 0.027임

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,5.000000,5.000000,5.000000,5.0,5.000000,5.000000,5.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000
mean,0.032468,3.600000,4.162000,0.0,0.478400,6.865200,61.040000,5.229720,2.20000,244.800000,17.660000,395.632000,5.284000,29.980000
std,0.022778,8.049845,2.655159,0.0,0.033768,0.346716,12.402943,0.840081,0.83666,30.318311,1.393915,1.849235,2.346813,6.682963
min,0.006320,0.000000,2.180000,0.0,0.458000,6.421000,45.800000,4.090000,1.00000,222.000000,15.300000,392.830000,2.940000,21.600000
25%,0.027290,0.000000,2.180000,0.0,0.458000,6.575000,54.200000,4.967100,2.00000,222.000000,17.800000,394.630000,4.030000,24.000000
50%,0.027310,0.000000,2.310000,0.0,0.469000,6.998000,61.100000,4.967100,2.00000,242.000000,17.800000,396.900000,4.980000,33.400000
75%,0.032370,0.000000,7.070000,0.0,0.469000,7.147000,65.200000,6.062200,3.00000,242.000000,18.700000,396.900000,5.330000,34.700000
max,0.069050,18.000000,7.070000,0.0,0.538000,7.185000,78.900000,6.062200,3.00000,296.000000,18.700000,396.900000,9.140000,36.200000

## **value_counts() : 값 카운트**

In [64]:
df['RAD'].value_counts()      #RAD열의 값을 카운트

RAD
2    2
3    2
1    1
Name: count, dtype: int64

## **<font color=red>.str.</font>함수() : str 글자로 바꾸기**

In [65]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='str')

In [66]:
df.columns.str.lower()       # .str 글자로 바꾸고 .lower 소문자로

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='str')

# **★★★Grouping★★★**

## <font color=blue> **max(), min(), mean(), sum(), count(), std()**

In [67]:
#sample

df77 = df = pd.DataFrame(
    {
        "A": ["one", "one", "two", "three"] * 3,
        "B": ["A", "B", "C"] * 4,
        "C": ["foo", "foo", "foo", "bar", "bar", "bar"] * 2,
        "D": np.random.randn(12),
        "E": np.random.randn(12),
    }
)
df77.head(3)

     A  B    C         D         E
0  one  A  foo -0.549881 -0.261322
1  one  B  foo -1.678012  0.462023
2  two  C  foo  2.464938 -0.593596

In [68]:
df77.groupby("A")      # 메모리 주소가 찍힘

In [69]:
df77.groupby("A")["D"].sum()     #A그룹 중에서 D를 합해라

A
one     -0.516734
three    2.067385
two      2.995864
Name: D, dtype: float64

In [70]:
df77.groupby("A")["D"].min()    #최소값

A
one     -1.678012
three    0.572815
two     -1.011770
Name: D, dtype: float64

In [71]:
df77.groupby("A")["D"].agg(['min', 'max'])    #최소값/최대값을 agg 모으다

            min       max
A
one   -1.678012  1.334977
three  0.572815  0.886892
two   -1.011770  2.464938

In [72]:
df77.groupby("A").agg({"D":"min", "E":"max"})    #D는 min, E는 max를 구해라(딕셔너리)

              D         E
A
one   -1.678012  0.462023
three  0.572815 -0.604776
two   -1.011770  1.037474

##  <font color=blue> **concat & merge**

### **pd.concat(axis=)**
* <font color=red><b> axis=0 : 행 합치기
* <font color=red><b> axis=1 : 열 합치기

In [73]:
dfa = pd.DataFrame ({"a" : [1,2,3], "b" : [10,20,30]})
dfb = pd.DataFrame ({"a" : [4,5], "b" : [40,50]})

In [74]:
dfa

   a   b
0  1  10
1  2  20
2  3  30

In [75]:
dfb

   a   b
0  4  40
1  5  50

In [76]:
dfab = pd.concat ( [dfa, dfb],  axis=0 )    #행에 추가, 인덱스 이름 주의
dfab

   a   b
0  1  10
1  2  20
2  3  30
0  4  40
1  5  50

In [77]:
dfab = pd.concat ( [dfa, dfb],  axis=0 ) 
dfab = dfab.reset_index()      #원래 인덱스를 밖으로 꺼내고 인덱스 재정리
dfab

   index  a   b
0      0  1  10
1      1  2  20
2      2  3  30
3      0  4  40
4      1  5  50

In [78]:
dfab = pd.concat ( [dfa, dfb],  axis=0 ) 
dfab = dfab.reset_index(drop=True)      #밖으로 꺼낸 원래 인덱스 지우고 인덱스 재정리
dfab

   a   b
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50

In [79]:
dfab = pd.concat ( [dfa, dfb],  axis=1 )    #열에 추가, 컬럼 이름 주의
dfab

   a   b    a     b
0  1  10  4.0  40.0
1  2  20  5.0  50.0
2  3  30  NaN   NaN

In [80]:
dfab = pd.concat ( [dfa, dfb],  axis=1 )
dfab.columns = ['a', 'b', 'c', 'd']           #컬럼 이름 변경
dfab

   a   b    c     d
0  1  10  4.0  40.0
1  2  20  5.0  50.0
2  3  30  NaN   NaN

### **pd.merge(dfa, dfb, on="컬럼", how="inner/outer")**
* <font color=red><b> inner : 서로 일치하는 게 있으면 합쳐
* <font color=red><b> outer : 일치하는 게 없으면 비워놔
* concat과의 차이 : 인덱스/컬럼 네이밍 자동

* <font color=blue><b> 컬럼이 아닌 인덱스로 merge

In [81]:
dfa = pd.merge(dfa, dfb, left_index=True, right_index=True, how="inner")      #왼쪽(dfa)인덱스 사용? 오른쪽(dfb)인덱스 사용? / 일치하는게 있으면 합쳐라
dfab

   a   b    c     d
0  1  10  4.0  40.0
1  2  20  5.0  50.0
2  3  30  NaN   NaN

In [82]:
dfa = pd.merge(dfa, dfb, left_index=True, right_index=True, how="outer") 
dfab

   a   b    c     d
0  1  10  4.0  40.0
1  2  20  5.0  50.0
2  3  30  NaN   NaN

* <font color=blue><b> 컬럼으로 merge

In [83]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})

In [84]:
left

   key  lval
0  foo     1
1  foo     2

In [85]:
right

   key  rval
0  foo     4
1  foo     5

In [86]:
dfab = pd.merge(left, right, on="key", how="inner")     #foo에 해당하는 게 두개기 때문에 총 네개가 나오는 거
dfab

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

In [87]:
left = pd.DataFrame({"key": ["foo", "foo2"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "foo2"], "rval": [4, 5]})

In [88]:
dfab = pd.merge(left, right, on="key", how="inner")              #foo와 foo2로 구분했기 때문에 총 두개만 나옴
dfab

    key  lval  rval
0   foo     1     4
1  foo2     2     5

### **실습**

In [89]:
dfab = pd.concat( [dfa, dfb], axis=0)
dfab

   a_x   b_x  a_y   b_y  a   b
0  1.0  10.0  4.0  40.0  4  40
1  2.0  20.0  5.0  50.0  5  50
0  NaN   NaN  NaN   NaN  4  40
1  NaN   NaN  NaN   NaN  5  50

In [90]:
dfab = pd.concat( [dfa, dfb], axis=1)
dfab

   a_x  b_x  a_y  b_y  a   b  a   b
0    1   10    4   40  4  40  4  40
1    2   20    5   50  5  50  5  50

In [91]:
dfab = pd.concat( [dfa, dfb], axis=1)
dfab = dfab.reset_index(drop=True)
dfab

   a_x  b_x  a_y  b_y  a   b  a   b
0    1   10    4   40  4  40  4  40
1    2   20    5   50  5  50  5  50

In [94]:
left = pd.DataFrame({"key": ["foo", "foo2"], "lval": [1, 2]})
right = pd.DataFrame({"key": ["foo", "foo2"], "rval": [4, 5]})
dfab = pd.merge(left, right, on="key", how="inner")
dfab

    key  lval  rval
0   foo     1     4
1  foo2     2     5