# **컨프리헨션**

* for문 1~10까지 짝수만 출력

In [6]:
for a in range (1, 11) :
    if ( a % 2 == 0) :
        print(a, end="  ")

2  4  6  8  10

* 컨프리헨션

In [7]:
[ a for a in range (1, 11) if ( a % 2 == 0) ]

[2, 4, 6, 8, 10]

* for문 1~5까지 3보다 크면 값*2, 그렇지 않으면 값 그대로

In [9]:
for a in range (1, 6) :
    if ( a > 3) :
        print(a*2, end="  ")
    else :
        print(a, end="  ")

1  2  3  8  10

* 컨프리헨션

In [10]:
[ a*2 if ( a > 3) else a for a in range (1, 6) ]

[1, 2, 3, 8, 10]

# **람다(Lambda)**
* 익명 함수 (이름이 없는)
* 1회용

* 함수이름 : add
* 파라미터 : 숫자 2개
* 리턴 : 합한 결과

In [17]:
def add(n1, n2) : 
    res = n1 + n2
    return res

In [18]:
a = add(4, 5)
print(a)

9

In [19]:
def ncheck(n) :
    print(n*2)

ncheck(6)

12

* <b> 람다 예제

In [25]:
ncheck2 = lambda n : n*2

In [26]:
ncheck2(6)

12

* <b> 람다 예제2

In [27]:
def add(n1, n2) : 
    res = n1 + n2
    return res
    
a = add(4, 5)
print(a)

9

In [28]:
add2 = lambda n1, n2 : n1 + n2
add2(4, 5)

9

* <b> 람다 예제3 + 컨프리헨션

In [34]:
a = lambda n : n if n > 10 else 0
a (3)

0

# **DataFrame을 활용한 람다(Lambda)**

In [36]:
import numpy as np
import pandas as pd

In [38]:
df = pd.DataFrame({
    "name": ["kim", "hong", "park"],
    "age": [20, 25, 30]
})
df

   name  age
0   kim   20
1  hong   25
2  park   30

In [39]:
df["age"] = df["age"] + 10
df

   name  age
0   kim   30
1  hong   35
2  park   40

In [40]:
df["age"] = df["age"].apply(lambda a : a+10)
df

   name  age
0   kim   40
1  hong   45
2  park   50

In [41]:
df["etc"] = df["age"].apply(lambda a : '성인' if a>=45 else '미성년')
df

   name  age  etc
0   kim   40  미성년
1  hong   45   성인
2  park   50   성인